projet_homepage:
    path:     /
    defaults: { _controller: ProjetBundle:Default:index }
projet_incident_create:
    path:     /formulaire_incident
    defaults: { _controller: ProjetBundle:Incident:create }
projet_incident_bidule:
    path:     /ping
    defaults: { _controller: ProjetBundle:Incident:bidule }
