services:
#    projet.example:
#        class: ProjetSymfony\ProjetBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    acme_hello.topic_sample_service:
        class: ProjetSymfony\ProjetBundle\Topic\SocketTopic